services:
  db:
    image: postgres:16
    container_name: carparks-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
  app:
    build: .
    container_name: carpark-app
    depends_on:
      - db
    environment:
      DS_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      DS_USER: ${DB_USER}
      DS_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: always
