services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
    ports:
      - "8080:8080"
  init:
    image: curlimages/curl:8.7.1
    depends_on:
      app:
        condition: service_started
    entrypoint: [ "/bin/sh","-c" ]
    command: >
      "until curl -sf http://app:8080/actuator/health; do echo 'waiting app'; sleep 2; done &&
       echo 'running import' &&
       curl -s -X GET http://app:8080/api/v1/util/import-carparks &&
       echo 'running availability' &&
       curl -s -X GET http://app:8080/api/v1/util/update-availability &&
       echo 'done'"
