spring:
  datasource:
    url: ${DS_URL}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: WegoCarParksHikariCP

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:validate}
    show-sql: true
