spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:wego_carparks}
    username: ${DB_USERNAME:wego}
    password: ${DS_PASSWORD:wegoPassw0rd}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: WegoCarParksHikariCP
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
carpark:
  availability-url: https://api.data.gov.sg/v1/transport/carpark-availability
