-- Create car_parks table
CREATE TABLE IF NOT EXISTS car_parks (
                                         id VARCHAR(50) PRIMARY KEY,
    address TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    svy21x DOUBLE PRECISION,
    svy21y DOUBLE PRECISION
    total_lots INT NOT NULL,
    );

create table public.car_park_availability
(
    id             bigint generated by default as identity
        primary key,
    available_lots integer not null,
    last_updated   timestamp(6) with time zone,
    car_park_id    varchar(255)
        constraint fkvwmxmthoeu4leksmn3uke2ft
            references public.car_parks
);

alter table public.car_park_availability
    owner to wego;

create unique index uniq_cpa_carparkid
    on public.car_park_availability (car_park_id);
